# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5U775_is0lWbJUjjJV5xLmXgonVas3U
"""

# Установка нужных библиотек
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings('ignore')

print("TensorFlow версия:", tf.__version__)
print("Библиотеки загружены успешно!")

# Загрузка данных (файл .xls, первая строка - лишний заголовок, пропускаем)
df = pd.read_excel('/content/default of credit card clients.xls',
                   header=1)  # header=1 пропускает первую строку

print("Размер датасета:", df.shape)
print("\nПервые 5 строк:")
df.head()

# Общая информация о датасете
print("=== Информация о датасете ===")
print(df.info())

print("\n=== Пропущенные значения ===")
print(df.isnull().sum())

print("\n=== Статистика целевой переменной ===")
print(df['default payment next month'].value_counts())
print("\nДоля дефолтов:", round(df['default payment next month'].mean() * 100, 2), "%")

# Переименуем целевую колонку для удобства
df = df.rename(columns={'default payment next month': 'target'})

# Удалим колонку ID - она не несёт смысла для модели
df = df.drop(columns=['ID'])

print("\n✅ Данные очищены. Итоговый размер:", df.shape)

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Распределение целевой переменной
axes[0].bar(['Нет дефолта (0)', 'Дефолт (1)'],
            df['target'].value_counts().values,
            color=['steelblue', 'tomato'])
axes[0].set_title('Распределение классов')
axes[0].set_ylabel('Количество')

# Распределение возраста
axes[1].hist(df['AGE'], bins=30, color='steelblue', edgecolor='white')
axes[1].set_title('Распределение возраста')
axes[1].set_xlabel('Возраст')
axes[1].set_ylabel('Количество')

# Дефолт по полу
sex_default = df.groupby('SEX')['target'].mean() * 100
axes[2].bar(['Мужчины (1)', 'Женщины (2)'],
            sex_default.values,
            color=['steelblue', 'tomato'])
axes[2].set_title('Доля дефолтов по полу, %')
axes[2].set_ylabel('Процент дефолтов')

plt.tight_layout()
plt.savefig('data_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ График сохранён как data_analysis.png")

from sklearn.utils.class_weight import compute_class_weight

# Признаки и целевая переменная
X = df.drop(columns=['target'])
y = df['target']

# Разбивка на train/val/test (70% / 15% / 15%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3,
                                                     random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5,
                                                  random_state=42, stratify=y_temp)

# Нормализация признаков
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

# Веса классов для борьбы с дисбалансом
class_weights = compute_class_weight('balanced',
                                      classes=np.unique(y_train),
                                      y=y_train)
class_weight_dict = dict(enumerate(class_weights))

print("Размеры выборок:")
print(f"  Train: {X_train_scaled.shape}")
print(f"  Val:   {X_val_scaled.shape}")
print(f"  Test:  {X_test_scaled.shape}")
print(f"\nВеса классов: {class_weight_dict}")

# Сохраняем scaler для веб-сервиса
import pickle
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("\n✅ Scaler сохранён в scaler.pkl")

# Построение модели
model = Sequential([
    Dense(256, activation='relu', input_shape=(23,)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.2),

    Dense(1, activation='sigmoid')  # бинарная классификация
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

model.summary()

# Ранняя остановка чтобы не переобучиться
early_stop = EarlyStopping(monitor='val_auc', patience=10,
                            mode='max', restore_best_weights=True)

# Обучение
print("\n🚀 Начинаем обучение...")
history = model.fit(
    X_train_scaled, y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=100,
    batch_size=512,
    class_weight=class_weight_dict,
    callbacks=[early_stop],
    verbose=1
)

print("\n✅ Обучение завершено!")

# График обучения
fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].plot(history.history['auc'], label='Train AUC', color='steelblue')
axes[0].plot(history.history['val_auc'], label='Val AUC', color='tomato')
axes[0].set_title('AUC по эпохам')
axes[0].set_xlabel('Эпоха')
axes[0].set_ylabel('AUC')
axes[0].legend()

axes[1].plot(history.history['loss'], label='Train Loss', color='steelblue')
axes[1].plot(history.history['val_loss'], label='Val Loss', color='tomato')
axes[1].set_title('Loss по эпохам')
axes[1].set_xlabel('Эпоха')
axes[1].set_ylabel('Loss')
axes[1].legend()

plt.tight_layout()
plt.savefig('training_history.png', dpi=150, bbox_inches='tight')
plt.show()

# Оценка на тестовой выборке
y_pred_prob = model.predict(X_test_scaled).flatten()
y_pred = (y_pred_prob >= 0.5).astype(int)

print("=== Метрики на тестовой выборке ===")
print(classification_report(y_test, y_pred,
      target_names=['Нет дефолта', 'Дефолт']))
print(f"ROC-AUC: {roc_auc_score(y_test, y_pred_prob):.4f}")

# Матрица ошибок
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Нет дефолта', 'Дефолт'],
            yticklabels=['Нет дефолта', 'Дефолт'])
plt.title('Матрица ошибок')
plt.ylabel('Истинный класс')
plt.xlabel('Предсказанный класс')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# Сохранение модели
model.save('credit_default_model.h5')
print("\n✅ Модель сохранена в credit_default_model.h5")

# Сохраняем в новом формате keras (рекомендуемый)
model.save('credit_default_model.keras')
print("✅ Модель сохранена в credit_default_model.keras")

# Сохранение списка признаков
import json
feature_names = list(X.columns)
with open('feature_names.json', 'w') as f:
    json.dump(feature_names, f)
print("✅ Признаки сохранены в feature_names.json")
print("Признаки:", feature_names)

